In [ ]:
import numpy as np

In [ ]:
# 1. 1'den 10'a kadar bir Numpy dizisi oluşturun

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# 2. 2 boyutlu bir Numpy dizisi oluşturun

a = np.array([[1, 2],
             [3,4]])

a.ndim

2

In [ ]:
# 3. Boyutları 2x3 olan bir Numpy dizisinin satır sayısını bulun

b = np.array([[1, 2, 3],
              [4, 5, 6]])

b.shape[0]

2

In [ ]:
# 4. Boyutları 2x3 olan bir Numpy dizisinin sütun sayısını bulun

b = np.array([[1, 2, 3],
              [4, 5, 6]])

b.shape[1]

3

In [ ]:
# 5. Bir Numpy dizisindeki en büyük değeri bulun

b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

b.max()

10

In [ ]:
# 6. Bir Numpy dizisindeki en küçük değeri bulun

b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

b.min()

1

In [ ]:
# 7. Bir Numpy dizisindeki ortalamayı bulun

b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

b.mean()

5.5

In [ ]:
# 8. Bir Numpy dizisindeki standart sapmayı bulun

b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

b.std()

2.8722813232690143

In [ ]:
# 9. Bir Numpy dizisinde tekrar eden elemanları bulun

b = np.array([1, 2, 3, 4, 3, 6, 7, 8, 6, 10])
bUnique = []
bRepeat = []
for i in b:
  if i not in bUnique:
    bUnique.append(i)
  else: 
    bRepeat.append(i)

bRepeat

[3, 6]

In [ ]:
# 10. 2 boyutlu bir Numpy dizisindeki tüm elemanların toplamını bulun

a=np.array([[5,3],
           [4,6]])
a.sum()

18

In [ ]:
# 11. 2 boyutlu bir Numpy dizisindeki her bir satırdaki elemanların toplamını bulun

a=np.array([[5,3],
           [4,6]])

a.sum(axis=1)

array([ 8, 10])

In [ ]:
# 12. 2 boyutlu bir Numpy dizisindeki her bir sütundaki elemanların toplamını bulun

b=np.array([[5,3],
           [4,6]])

b.sum(axis=0)

array([9, 9])

In [ ]:
# 13. Numpy dizisi boyutlarını değiştirin

b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

b.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
# 14. Numpy dizisindeki elemanların transpozunu alın

a=np.array([[5,3],
           [4,6]])

a.T

array([[5, 4],
       [3, 6]])

In [ ]:
# 15. Numpy dizisindeki elemanların sıralamasını yapın

b = np.array([3, 6, 1, 7, 5, 2, 4, 10, 9, 8])
b.sort()
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# 16. 2 boyutlu bir Numpy dizisindeki her bir sütundaki elemanların ortalamasını bulun

a=np.array([[5,3],
           [4,6]])

a.mean(axis=0)

array([4.5, 4.5])

In [ ]:
# 17. 2 boyutlu bir Numpy dizisindeki her bir satırdaki elemanların standart sapmasını bulun

a=np.array([[15,3],
           [9,6]])

a.std(axis=1)

array([6. , 1.5])

In [ ]:
# 18. 2 boyutlu bir Numpy dizisinde belirli bir elemanın index değerini bulun

a=np.array([[5,3],
           [4,6]])



In [ ]:
# 19. 2 boyutlu bir Numpy dizisinde belirli bir sütunu seçin

a=np.array([[5,3],
           [4,6]])

a[:,0]

array([5, 4])

In [ ]:
# 20. 2 boyutlu bir Numpy dizisinde belirli bir satırı seçin

a=np.array([[5,3],
           [4,6]])

a[0,]

array([5, 3])